"""Hardware tests for YubiKey signing path.

These tests REQUIRE a physical YubiKey with a PIV application.  They are
marked ``hardware`` and excluded from the default pytest run.  Run them with::

    pytest -m hardware -v

or for a specific slot/PIN::

    YUBIKEY_SLOT=9c YUBIKEY_PIN=123456 pytest -m hardware -v

Expected device state
---------------------
- YubiKey plugged in and visible to pcscd
- PIV slot 9c (SIGNATURE) contains a key — either pre-existing or freshly
  generated by the ``test_setup_yubikey_slot`` test
- pcscd running: ``sudo systemctl start pcscd``

Under WSL2
----------
USB passthrough via usbipd-win is required; see BUILDING.md.

Failure modes
-------------
- ``ImportError`` — yubikey-manager not installed: ``pip install 'torchbase[yubikey]'``
- ``DeviceNotFoundError`` — no YubiKey detected (pcscd not running, device
  not attached, or usbipd attachment dropped)
- ``ApduError`` / ``InvalidPinError`` — wrong PIN or slot has no key
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# Marker — all tests in this file require physical hardware
# ---------------------------------------------------------------------------

pytestmark = pytest.mark.hardware

REPO_ROOT = Path(__file__).parent.parent.parent
EXAMPLE_TORCH = REPO_ROOT / "examples" / "simple_mlst" / "1.0.0.torch"

SLOT = os.environ.get("YUBIKEY_SLOT", "9c")
PIN  = os.environ.get("YUBIKEY_PIN", "123456")


def _make_torch(tmp_path: Path) -> Path:
    torch_dir = tmp_path / "examples" / "simple_mlst" / "1.0.0.torch"
    shutil.copytree(EXAMPLE_TORCH, torch_dir)
    return torch_dir


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def yubikey_signer():
    """Return a YubiKeySigner for the configured slot.

    Fails immediately (not skipped) if ykman is missing or the device is absent.
    """
    from torchbase.signing import YubiKeySigner
    return YubiKeySigner(slot=SLOT, pin=PIN)


# ---------------------------------------------------------------------------
# Import and instantiation
# ---------------------------------------------------------------------------

class TestYubiKeySignerInit:
    def test_import(self):
        """ykman package must be importable."""
        from torchbase.signing import YubiKeySigner
        assert YubiKeySigner is not None

    def test_instantiation_connects(self, yubikey_signer):
        """Constructor must succeed — device is present and accessible."""
        from torchbase.signing import YubiKeySigner
        assert isinstance(yubikey_signer, YubiKeySigner)

    def test_algorithm_detected(self, yubikey_signer):
        """Algorithm must be one of the supported values."""
        assert yubikey_signer.algorithm in ("ed25519", "p256")

    def test_missing_ykman_raises_import_error(self, monkeypatch):
        """If ykman is not available, __init__ raises ImportError (not crashes)."""
        import builtins
        real_import = builtins.__import__

        def _block_ykman(name, *args, **kwargs):
            if name in ("ykman.device", "yubikit.piv"):
                raise ImportError("blocked for test")
            return real_import(name, *args, **kwargs)

        monkeypatch.setattr(builtins, "__import__", _block_ykman)

        from torchbase.signing import YubiKeySigner
        with pytest.raises(ImportError, match="yubikey-manager"):
            YubiKeySigner(slot=SLOT, pin=PIN)


# ---------------------------------------------------------------------------
# Public key export
# ---------------------------------------------------------------------------

class TestYubiKeyPublicKey:
    def test_public_key_bytes_returns_bytes(self, yubikey_signer):
        pub = yubikey_signer.public_key_bytes()
        assert isinstance(pub, bytes)
        assert len(pub) > 0

    def test_public_key_length_matches_algorithm(self, yubikey_signer):
        pub = yubikey_signer.public_key_bytes()
        if yubikey_signer.algorithm == "ed25519":
            assert len(pub) == 32, "Ed25519 public key must be 32 bytes"
        elif yubikey_signer.algorithm == "p256":
            assert len(pub) == 65, "P-256 uncompressed point must be 65 bytes (04 || x || y)"

    def test_public_key_is_base64url_encodable(self, yubikey_signer):
        from torchbase.signing import _b64u, _b64u_decode
        pub = yubikey_signer.public_key_bytes()
        encoded = _b64u(pub)
        assert _b64u_decode(encoded) == pub


# ---------------------------------------------------------------------------
# Signing
# ---------------------------------------------------------------------------

class TestYubiKeySigning:
    def test_sign_returns_bytes(self, yubikey_signer):
        sig = yubikey_signer.sign(b"test message")
        assert isinstance(sig, bytes)
        assert len(sig) > 0

    def test_sign_is_deterministic_ed25519(self, yubikey_signer):
        """Ed25519 signatures are deterministic; same message → same sig."""
        if yubikey_signer.algorithm != "ed25519":
            pytest.skip("determinism test only applies to Ed25519")
        msg = b"determinism check"
        sig1 = yubikey_signer.sign(msg)
        sig2 = yubikey_signer.sign(msg)
        assert sig1 == sig2

    def test_sign_different_messages_differ(self, yubikey_signer):
        sig1 = yubikey_signer.sign(b"message one")
        sig2 = yubikey_signer.sign(b"message two")
        assert sig1 != sig2

    def test_signature_verifies(self, yubikey_signer):
        """Signature produced by the device must verify against its public key."""
        from torchbase.signing import _verify_signature, _b64u
        msg = b"hardware verification test"
        sig = yubikey_signer.sign(msg)
        pub = yubikey_signer.public_key_bytes()
        # Should not raise
        _verify_signature(msg, sig, pub, yubikey_signer.algorithm)

    def test_signature_fails_with_wrong_key(self, yubikey_signer, tmp_path):
        """Signature from YubiKey must not verify against a different key."""
        from torchbase.signing import (
            _verify_signature, generate_software_keypair, FileKeySigner, _b64u_decode
        )
        msg = b"wrong key test"
        sig = yubikey_signer.sign(msg)

        priv, pub = generate_software_keypair("other", tmp_path)
        wrong_pub_raw = _b64u_decode(pub.read_text().strip())

        with pytest.raises(Exception):
            _verify_signature(msg, sig, wrong_pub_raw, "ed25519")


# ---------------------------------------------------------------------------
# Torch signing round-trip
# ---------------------------------------------------------------------------

class TestYubiKeyTorchSigning:
    def test_sign_torch_creates_signature_toml(self, yubikey_signer, tmp_path):
        from torchbase.signing import sign_torch
        torch_dir = _make_torch(tmp_path)
        sig_path = sign_torch(torch_dir, yubikey_signer)
        assert sig_path.exists()

        import toml
        data = toml.load(sig_path)
        assert "signature" in data
        assert data["signature"]["algorithm"] == yubikey_signer.algorithm

    def test_verify_torch_with_hardware_signature(self, yubikey_signer, tmp_path):
        from torchbase.signing import sign_torch, verify_torch
        torch_dir = _make_torch(tmp_path)
        sign_torch(torch_dir, yubikey_signer)

        from torchbase.signing import _b64u
        pub_b64 = _b64u(yubikey_signer.public_key_bytes())
        result = verify_torch(torch_dir, public_key_b64=pub_b64)
        assert result.valid, f"Verification failed: {result.message}"

    def test_verify_torch_embedded_key(self, yubikey_signer, tmp_path):
        """Embedded public_key in signature.toml is sufficient for verification."""
        from torchbase.signing import sign_torch, verify_torch
        torch_dir = _make_torch(tmp_path)
        sign_torch(torch_dir, yubikey_signer)
        result = verify_torch(torch_dir)
        assert result.valid, f"Verification failed: {result.message}"

    def test_tampered_torch_fails_verification(self, yubikey_signer, tmp_path):
        from torchbase.signing import sign_torch, verify_torch
        torch_dir = _make_torch(tmp_path)
        sign_torch(torch_dir, yubikey_signer)
        (torch_dir / "profiles.tsv").open("a").write("\ntamper\n")

        from torchbase.signing import _b64u
        pub_b64 = _b64u(yubikey_signer.public_key_bytes())
        result = verify_torch(torch_dir, public_key_b64=pub_b64)
        assert not result.valid


# ---------------------------------------------------------------------------
# CID signing
# ---------------------------------------------------------------------------

class TestYubiKeyCidSigning:
    def test_sign_and_verify_cid(self, yubikey_signer):
        from torchbase.signing import sign_cid, verify_cid, _b64u
        cid = "QmHardwareTest123abc"
        namespace = "examples"
        version = "1.0.0"
        pub_b64 = _b64u(yubikey_signer.public_key_bytes())

        sig = sign_cid(cid, namespace, version, yubikey_signer)
        assert verify_cid(cid, namespace, version, sig, pub_b64, yubikey_signer.algorithm)

    def test_cid_sig_wrong_cid_fails(self, yubikey_signer):
        from torchbase.signing import sign_cid, verify_cid, _b64u
        pub_b64 = _b64u(yubikey_signer.public_key_bytes())
        sig = sign_cid("QmReal", "examples", "1.0.0", yubikey_signer)
        assert not verify_cid("QmFake", "examples", "1.0.0", sig, pub_b64, yubikey_signer.algorithm)


# ---------------------------------------------------------------------------
# _piv_slot helper
# ---------------------------------------------------------------------------

class TestPivSlot:
    def test_all_slots_resolve(self):
        """_piv_slot must resolve all four canonical slot strings."""
        # Import ykman so we get the real SLOT constants, not a stub
        from yubikit.piv import SLOT
        from torchbase.signing import _piv_slot
        assert _piv_slot("9a") == SLOT.AUTHENTICATION
        assert _piv_slot("9c") == SLOT.SIGNATURE
        assert _piv_slot("9d") == SLOT.KEY_MANAGEMENT
        assert _piv_slot("9e") == SLOT.CARD_AUTH

    def test_unknown_slot_raises(self):
        from torchbase.signing import _piv_slot
        with pytest.raises(KeyError):
            _piv_slot("ff")


# ---------------------------------------------------------------------------
# setup_yubikey_slot
# ---------------------------------------------------------------------------

class TestSetupYubiKeySlot:
    def test_generates_key_and_writes_pub(self, tmp_path):
        """Generating a key on the device writes a .pub file."""
        from torchbase.signing import setup_yubikey_slot, _b64u_decode
        pub_path = setup_yubikey_slot(SLOT, "testns", tmp_path, pin=PIN)
        assert pub_path.exists()
        raw = _b64u_decode(pub_path.read_text().strip())
        # P-256 uncompressed point is 65 bytes; Ed25519 raw key is 32 bytes
        assert len(raw) in (32, 65)
